name:  pull Docker Images

on:
  push:
    branches:
      - main

jobs:
  trigger-repo-and-pull-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: trigger chatapp repo to build-and-push image
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN_TO_TRIGGER }}
          repository: olawaleade/chatapp
          event-type: my-event
      
      - name: Pull Latest Docker Images
        if: ${{ github.event_name == 'repository_dispatch' && github.event.event.client_payload.message == 'Build and push successful' }}
        run: |
          docker pull olawde/backend:${{ github.event.client_payload.timestamp }}
          docker pull olawde/frontend:${{ github.event.client_payload.timestamp }}
